### ISSUE TITLE
Python3 Compatability

### ISSUE THREAD

**Issue by devdupont** [switchdoclabs/iBeacon-Scanner-#2]
I tried finding a better way to contact you, but to no avail. Anyway...

I played with the iBeacon Scanner and got it working on a Raspberry Pi. However, because I've moved to Python3, I had to work with the file a little bit. The Python3 implementation of buffer read/write is different than Python2. I also went in and cleaned up the code so that only the necessary elements remained. That included removing commented code and a slew of unused variables. I left the unused config variables in but commented out. I made it so that the beacon return list doesn't include any duplicates. I also merged the test code into the main file using if **name** == '**main**'

Here's a link to the file hosted in Dropbox so you can give it a look:
https://www.dropbox.com/s/cxck4jnm9nja7y6/blescan.py?dl=0

**Comment by sanmarz** [comment]
I clicked on your link above, and the file is gone.  Is the file available?  Thank you very much

**Comment by devdupont** [comment]
Links change after 8 months :)
Here it is in the project repo:
https://github.com/flyinactor91/RasPi-iBeacons/blob/master/blescan.py

**Comment by sanmarz** [comment]
Thanks!  I was debugging for python3, but I am just learning python, so this updated file will be a great help!

-Sandra

**Comment by sanmarz** [comment]
Hi Michael,

I get the same error with the latest code you sent me.  I installed the packages below to get rid of other errors: 

> sudo apt-get install python-bluez

I downloaded PyBluez-0.20, unzipped it, and ran “unzip PyBluez-0.20.zip”.  

I also installed “requests”.

> python3.2 testblescan.py

ble thread started

Traceback (most recent call last):

  File "testblescan.py", line 24, in <module>

```
blescan.hci_enable_le_scan(sock) 
```

  File "/home/pi/Desktop/blescan.py", line 82, in hci_enable_le_scan

```
hci_toggle_le_scan(sock, 0x01)
```

  File "/home/pi/Desktop/blescan.py", line 106, in hci_toggle_le_scan

```
bluez.hci_send_cmd(sock, OGF_LE_CTL, OCF_LE_SET_SCAN_ENABLE, cmd_pkt)
```

_bluetooth.error: (1, 'Operation not permitted')

I am stuck with this last error above.  Any help would be greatly appreciated?

Thank you very much,

Sandra

From: Sandra Marzola Jones [mailto:sandra@marzones.com] 
Sent: Friday, December 4, 2015 9:06 AM
To: 'switchdoclabs/iBeacon-Scanner-' reply@reply.github.com
Subject: RE: [iBeacon-Scanner-] Python3 Compatability (#2)

Thanks!  I was debugging for python3, but I am just learning python, so this updated file will be a great help!

-Sandra

**Comment by devdupont** [comment]
Requests is not required for blescan. Make sure you installed python3-bluez.
You likely need to run `sudo python3 blescan.py` so that bluez has full permissions to work with the hardware

**Comment by sanmarz** [comment]
I ran blescan.py by calling it with testblescan.py.  I received an error due to the line, "import requests" which I think was in blescan.py?  Maybe, I will comment it out then?
 
I will try your recommendations later today.
 
Thanks,
Sandra 
 

-------- Original Message --------Subject: Re: [iBeacon-Scanner-] Python3 Compatability (#2)From: Michael duPont notifications@github.comDate: Fri, December 04, 2015 10:03 amTo: switchdoclabs/iBeacon-Scanner- iBeacon-Scanner-@noreply.github.comCc: sanmarz sandra@marzones.com
Requests is not required for blescan. Make sure you installed python3-bluez.You likely need to run sudo python3 blescan.py so that bluez has full permissions to work with the hardware

**Comment by devdupont** [comment]
You're getting these two repos confused. I upgraded blescan to Python3 for use in my own repo. It might not work as is with testblescan. That's why if added if **main** to blescan because it acts as the test. If you need help, open up an issue on my repo that has the upgraded file.
