### ISSUE TITLE
txpower - # commented out - don't know what this byte is.  

### ISSUE THREAD

**Issue by gcphost** [switchdoclabs/iBeacon-Scanner-#3]
Hey, first of all let me start by thank you for sharing your code, it's helped me move forward in a project I am working on.

I am writing because I was looking into finding txpower and noticed you commented:
# commented out - don't know what this byte is.  It's NOT TXPower

```
                    txpower, = struct.unpack("b", pkt[report_pkt_offset -2])
                    print "\t(Unknown):", txpower
```

But it's not commented out.

Is txpower really txpower? 

Thanks!

**Comment by virtualguy** [comment]
From what I can tell it should be the tx power of the advertising device. It is up to the advertising device to set this value correctly and it is likely some beacons will not implement it.

**Comment by gcphost** [comment]
Awesome, thanks.
