### ISSUE TITLE
unpack beacon name

### ISSUE THREAD

**Issue by SKVasanth** [switchdoclabs/iBeacon-Scanner-#8]
I wanted to unpack beacon name from the pkt, have tried several methods but nothing is working out. Could you guys please help me on this topic. I am new bee in python. Refer attached image.

Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/13313162/16609802/83a9222a-4374-11e6-9dab-b5de602ab800.png)

**Comment by SKVasanth** [comment]
Hi, I am getting beacon name with other values by executing below line,
**struct.unpack(">xxBB%dp" % (len(pkt) - 4), pkt)**
Now, I wanted to have only name by filtering all other junk values
Example: Name - **INSITEO BABEFEEDO292**
Please refer attached image and any help is highly appreciated, Thanks in advance.
![image](https://cloud.githubusercontent.com/assets/13313162/16617759/25c63a7e-43a3-11e6-84f5-f04822c31f2b.png)

**Comment by SKVasanth** [comment]
Hi, I didn't get any specific logic to extract name, Therefore I looped it as a normal string to extract name.
Thanks.

**Comment by uzunanil** [comment]
@SKVasanth Hi, I couldn't extract the name by using this code. Can you suggest another way to find it ??
